#!/bin/bash
# skript to generate rrd files
# generated by 
# ./metacreate_pack56_rrd.pl  \
/usr/bin/rrdtool create pack56.rrd --start NOW --step 5  \
DS:Vtot:GAUGE:10:0:80  \
DS:Ah:GAUGE:10:-100:1000  \
DS:Wh:GAUGE:10:-1000:50000  \
RRA:AVERAGE:0.5:2:86400  \
RRA:MIN:0.5:60:26000  \
RRA:MAX:0.5:60:26000  \
RRA:AVERAGE:0.5:60:26000  \
RRA:MIN:0.5:720:10000  \
RRA:MAX:0.5:720:10000  \
RRA:AVERAGE:0.5:720:10000  \
RRA:MIN:0.5:17280:22000  \
RRA:MAX:0.5:17280:22000  \
RRA:AVERAGE:0.5:17280:22000  \
